 baseURL: 'http://example.org/'
languageCode: en-us
paginate: 6
theme: portio
title: Portio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Service
      url: '#service'
      weight: 3
    - name: Work
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Skills
      url: '#skills'
      weight: 6
    - name: Blog
      url: '#blog'
      weight: 7
    - name: Contact
      url: '#contact'
      weight: 8
  sitemap:
    - name: About me
      url: about
      weight: 1
    - name: Frequently Ask Question
      url: '#'
      weight: 2
    - name: Privacy & Policy
      url: '#'
      weight: 3
    - name: Latest Article
      url: '#'
      weight: 4
params:
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright © Portio 2020
  footerLogo: images/contact/widget-logo.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.png
  address:
    address: '23 Khan Niketon, Grand Street, NYK.'
    email: hello@example.com
    openingHours: Open from 10am to 6pm (close at 5pm Sundays)
    phone: +(448) 833 5272 332
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: '23.7783741'
    longitude: '90.3746808'
    pinImage: images/pin.png
  social:
    - icon: fa-facebook-official
      url: 'https://www.facebook.com/'
      weight: 1
    - icon: fa-linkedin-square
      url: 'https://www.linkedin.com/'
      weight: 2
    - icon: fa-pinterest-square
      url: 'https://www.pinterest.com/'
      weight: 3
    - icon: fa-twitter-square
      url: 'https://twitter.com/'
      weight: 4
